# Generated by Django 4.1.5 on 2023-01-21 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trades',
            fields=[
                ('time', models.DateTimeField()),
                ('contract', models.CharField(max_length=10)),
                ('side', models.CharField(choices=[('Sell', 'Sell')], max_length=4)),
                ('filled_amount', models.IntegerField()),
                ('fill_price', models.DecimalField(decimal_places=6, max_digits=8)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=5)),
                ('order', models.CharField(choices=[('Market', 'Market')], max_length=6)),
                ('market', models.CharField(choices=[('Futures', 'Futures')], max_length=7)),
                ('transaction_id', models.CharField(max_length=24, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
