# Generated by Django 4.1.5 on 2023-01-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_rename_trades_trade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='side',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Buy'), (1, 'Sell')]),
        ),
    ]
