# Generated by Django 4.1.5 on 2023-01-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_alter_trade_side'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='market',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Spot'), (1, 'Futures')]),
        ),
        migrations.AlterField(
            model_name='trade',
            name='order',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Limit'), (1, 'Market')]),
        ),
    ]
